### ISSUE TITLE
Update the plugin repo to make it available for 2.10 (Pisa)

### ISSUE THREAD

**Issue by FranPregernik** [cayetanobv/QGIS-Plugin-MBTiles2img#1]
Hi,

could you please update the plugin repo page make it display for QGIS 2.10.

QGIS Pisa hardcodes the parameter ?qgis=2.10 when querying the repo.

Br,
Fran

**Comment by cayetanobv** [comment]
Hi Fran,

I just installed (previously uninstalling) this plugin without  problems in 2.10 (Pisa). Which is exactly what I should change in repo page? I don't know what to do.

Thanks!
Cayetano,

**Comment by FranPregernik** [comment]
Hi Cayetano,

That's strange. It doesn't even show up in my list in QGIS. I had to manually install it.

Maybe my install is messed up somehow.

We can close this issue as far as I am concerned.

Br,
Fran

**Comment by cayetanobv** [comment]
Hi Fran,

Maybe you don't have checked the option "Show also experimental plugins" on QGIS plugins settings window. If you check this box I think you can see the pugin in QGIS Pisa (and all the experimental plugins). Anyway, the plugin has been running well enough time, so I'll remove it from the category of experimental. Thank you for reminding me.

Cayetano

**Comment by FranPregernik** [comment]
OMG I totaly missed that checkbox :D
Glad to help.

Say, do you know of a QGIS -> MBTiles exporter?
I have a raster map (scanned and georeferenced) that I wish to export so that OruxMaps can read it and one of the options is MBTiles.

**Comment by cayetanobv** [comment]
Hi Fran,

Yes, it exists a plugin for that. My plugin (MBTiles2img) is the reverse process: from a MBTiles file you can extract all the images contained in. The plugin which you can use to produce MBTiles from QGIS is QTiles, developed by NextGIS people:
https://github.com/nextgis/QTiles
You can install it from QGIS plugins manager.This plugins works fine.

Cayetano,
